In [38]:
import requests
import pandas as pd
from io import StringIO

In [39]:
url = "https://en.wikipedia.org/wiki/List_of_highest-grossing_films"

headers = {
    "User-Agent": "Mozilla/5.0"
}

response = requests.get(url, headers=headers)

In [40]:
tables = pd.read_html(StringIO(response.text))

movies = tables[0]

movies.head()

   Rank Peak                     Title   Worldwide gross  Year          Ref
0     1    1                    Avatar    $2,923,710,708  2009   [# 1][# 2]
1     2    1         Avengers: Endgame    $2,797,501,328  2019   [# 3][# 4]
2     3    3  Avatar: The Way of Water    $2,334,484,620  2022   [# 5][# 6]
3     4    1                   Titanic   T$2,257,906,828  1997   [# 7][# 8]
4     5    5                  Ne Zha 2  NZ$2,215,690,000  2025  [# 9][# 10]

In [41]:
movies = movies.drop(columns=["Ref"])

movies.head()

   Rank Peak                     Title   Worldwide gross  Year
0     1    1                    Avatar    $2,923,710,708  2009
1     2    1         Avengers: Endgame    $2,797,501,328  2019
2     3    3  Avatar: The Way of Water    $2,334,484,620  2022
3     4    1                   Titanic   T$2,257,906,828  1997
4     5    5                  Ne Zha 2  NZ$2,215,690,000  2025

In [42]:
movies.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 5 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Rank             50 non-null     int64
 1   Peak             50 non-null     object
 2   Title            50 non-null     object
 3   Worldwide gross  50 non-null     object
 4   Year             50 non-null     int64
dtypes: int64(2), object(3)
memory usage: 2.1+ KB

In [43]:
movies.to_csv("highest_grossing_films.csv", index=False)

print("CSV saved successfully!")

CSV saved successfully!

In [44]:
from google.colab import files

files.download("highest_grossing_films.csv")